name: Docker Image CI

on:
  push:
    branches: [ "preview_service" ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Build Productpage Image
#        run:  docker build -t lxwing/productpage:latest -f samples/bookinfo/src/productpage .
        run: cd istio && ls

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

#      - name: Push Image
#        run: |
#          docker push lxwing/productpage:latest